src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $titre;

    #[ORM\Column(type: 'text')]
    private $contenu;

    #[ORM\Column(type: 'datetime')]
    private $date_envoie;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private $destinataire;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateEnvoie(): ?\DateTimeInterface
    {
        return $this->date_envoie;
    }

    public function setDateEnvoie(\DateTimeInterface $date_envoie): self
    {
        $this->date_envoie = $date_envoie;

        return $this;
    }

    public function getDestinataire(): ?User
    {
        return $this->destinataire;
    }

    public function setDestinataire(?User $destinataire): self
    {
        $this->destinataire = $destinataire;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('contenu')

            ;
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use App\Repository\MessageRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\UserRepository;

#[Route('/message')]
class MessageController extends AbstractController
{
    #[Route('/', name: 'app_message_index', methods: ['GET'])]
    public function index(MessageRepository $messageRepository): Response
    {
        return $this->render('message/index.html.twig', [
            'messages' => $messageRepository->findAll(),
        ]);
    }

    #[Route("/new/{id}", name: 'app_message_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MessageRepository $messageRepository,$id,UserRepository $userRepository): Response
    {// récuperer le user par son id
        $user = $userRepository->find($id);
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //je recupère la date du jour
            $date_jour = new DateTime();
            // je  set l'object message avec la date du jour
            $message->setDateEnvoie($date_jour);
            $message->setDestinataire($user);
            $messageRepository->add($message, true);

            return $this->redirectToRoute('app_user', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('message/new.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_message_show', methods: ['GET'])]
    public function show(Message $message): Response
    {
        return $this->render('message/show.html.twig', [
            'message' => $message,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_message_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Message $message, MessageRepository $messageRepository): Response
    {
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $messageRepository->add($message, true);

            return $this->redirectToRoute('app_message_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('message/edit.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_message_delete', methods: ['POST'])]
    public function delete(Request $request, Message $message, MessageRepository $messageRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $messageRepository->remove($message, true);
        }

        return $this->redirectToRoute('app_message_index', [], Response::HTTP_SEE_OTHER);
    }
// cette methode qui  permet de choisir un objet et de le transformer  en string quand on l'appel
//solution1
    // public function __toString()
    // {
    //     return $this->nom ;
    // }

    //2eme methode on la fait directement dansmessage type ligne 20 a partir de Entity
}

templates/message/_delete_form.html.twig
<form method="post" action="{{ path('app_message_delete', {'id': message.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn">Delete</button>
</form>

templates/message/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/message/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Message{% endblock %}

{% block body %}
    <h1>Edit Message</h1>

    {{ include('message/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_message_index') }}">back to list</a>

    {{ include('message/_delete_form.html.twig') }}
{% endblock %}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message index{% endblock %}

{% block body %}
    <h1>Message index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Contenu</th>
                <th>Date_envoie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for message in messages %}
            <tr>
                <td>{{ message.id }}</td>
                <td>{{ message.titre }}</td>
                <td>{{ message.contenu }}</td>
                <td>{{ message.dateEnvoie ? message.dateEnvoie|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_message_show', {'id': message.id}) }}">show</a>
                    <a href="{{ path('app_message_edit', {'id': message.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_message_new') }}">Create new</a>
{% endblock %}

templates/message/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Message{% endblock %}

{% block body %}
    <h1>Create new Message</h1>

    {{ include('message/_form.html.twig') }}

    <a href="{{ path('app_user') }}">back to list</a>
{% endblock %}

templates/message/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message{% endblock %}

{% block body %}
    <h1>Message</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ message.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ message.titre }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ message.contenu }}</td>
            </tr>
            <tr>
                <th>Date_envoie</th>
                <td>{{ message.dateEnvoie ? message.dateEnvoie|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_message_index') }}">back to list</a>

    <a href="{{ path('app_message_edit', {'id': message.id}) }}">edit</a>

    {{ include('message/_delete_form.html.twig') }}
{% endblock %}