src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $nom;

    #[ORM\Column(type: 'string', length: 100)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse;

    #[ORM\Column(type: 'string', length: 100)]
    private $ville;

    #[ORM\Column(type: 'string', length: 10)]
    private $cp;

    #[ORM\Column(type: 'string', length: 100)]
    private $email;

    #[ORM\Column(type: 'string', length: 20, nullable: true)]
    private $tel;

    #[ORM\Column(type: 'float')]
    private $salaire;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $service;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_naissance;

    #[ORM\OneToMany(mappedBy: 'destinataire', targetEntity: Message::class,orphanRemoval:true)]
    private $messages;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getSalaire(): ?float
    {
        return $this->salaire;
    }

    public function setSalaire(float $salaire): self
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(?string $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $ye): self
    {
        if (!$this->messages->contains($ye)) {
            $this->messages[] = $ye;
            $ye->setDestinataire($this);
        }

        return $this;
    }

    public function removeMessages(Message $ye): self
    {
        if ($this->messages->removeElement($ye)) {
            // set the owning side to null (unless already changed)
            if ($ye->getDestinataire() === $this) {
                $ye->setDestinataire(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\AjouterUserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;




class UserController extends AbstractController
{
    #[Route('/liste_user', name: 'app_user')]
    public function index( UserRepository $userRepository): Response
    { //controler doit envoyer la liste utilisateur  a la  vue
        return $this->render('user/user.html.twig', [
            "liste_users" => $userRepository->findAll()
            
        
        ]);
    }
// methode pour allerchercher un seul utilisateur
    //code pour l'annotation pour passer un paramètre dans lurl
    #[Route("/profil-user/{id}", name: "app_detail_user")]
    public function getOneuser( $id,UserRepository $userRepository): Response
    { 
        return $this->render('user/show_user.html.twig', [
            "user" => $userRepository->find($id)
           
            
        
        ]);
    }



    // methode pour ajouter un user
    //code pour l'annotation pour passer un paramètre dans lurl
    #[Route("/ajouter-user", name: "app_add_user")]
    public function adduser(Request $request,UserRepository $userRepository,): Response
    { 
        //creer un objet de la classe user
        $user = new User();
        //je creer un formulaire et je le lie a nôtre objet  user on met :: pour prendre que le nom de la classe
        $form = $this->createForm(AjouterUserType::class,$user);
        //je met mon form a l'écoute des requette qui passe dans l'url
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $userRepository->add($user);
            return $this->redirectToRoute('app_user');

        }

        return $this->render('user/add_user.html.twig', 
        [
        
        "form" =>$form->createView()    
        
        ]
      );
    }





    // methode pour aller chercher un seul id
    #[Route("/delete-user/{id}", name: "app_delete_user")]
    public function deleteeuser( $id,UserRepository $userRepository): Response

    {// je récupère le user par son id avec la méthode find de UserRepo
         $user= $userRepository->find($id);
//je supprime le user avec la méthode remove  de userRepo
        $userRepository->remove($user);
        //je redirige vers la page user
        return $this->redirectToRoute('app_user');
        
    }

    
    #[Route("/modifier-user/{id}", name: "app_edit_user")]
    public function edituser($id , Request $request,UserRepository $userRepository,): Response
    { 
        $user = $userRepository->find($id);
        
        $form = $this->createForm(AjouterUserType::class,$user);
        
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $userRepository->add($user);
            return $this->redirectToRoute('app_user');

        }

        return $this->render('user/edit_user.html.twig', 
        [
        
        "form" =>$form->createView()    
        
        ]
      );
    }



    


}

templates/user/add_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<div class="container">
    <div class="col-md-6 mx-auto my-4">
    <h1 class="text-center text-muted my-3" >Ajouter un user</h1>
    {{ form_start(form) }}
        <div class="row">
            <div class="col-6">
                {{ form_row(form.nom) }}
            </div>
            <div class="col-6">
                {{ form_row(form.prenom) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">{{ form_row(form.email) }}</div>
            <div class="col-6">{{ form_row(form.tel) }}</div>
        </div>

        <div class="row">
            <div class="col">
                {{ form_row(form.adresse) }}
            </div>
        </div>

        <div class="row">
            <div class="col-8">
                {{ form_row(form.ville) }}
            </div>
            <div class="col-4">
                {{ form_row(form.cp) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">{{ form_row(form.salaire) }}</div>
            <div class="col-6">{{ form_row(form.service) }}</div>
        </div>

         <div class="row">
            <div class="col">
                {{ form_row(form.date_naissance) }}
            </div>
        </div>
    <input type="submit" value="ajouter" class='btn btn-dark' >
    {{ form_end(form) }}
    </div>
</div>

{% endblock %}

templates/user/edit_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<div class="container">
    <div class="col-md-6 mx-auto my-4">
    <h1 class="text-center text-muted my-3" >Ajouter un user</h1>
    {{ form_start(form) }}
        <div class="row">
            <div class="col-6">
                {{ form_row(form.nom) }}
            </div>
            <div class="col-6">
                {{ form_row(form.prenom) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">{{ form_row(form.email) }}</div>
            <div class="col-6">{{ form_row(form.tel) }}</div>
        </div>

        <div class="row">
            <div class="col">
                {{ form_row(form.adresse) }}
            </div>
        </div>

        <div class="row">
            <div class="col-8">
                {{ form_row(form.ville) }}
            </div>
            <div class="col-4">
                {{ form_row(form.cp) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">{{ form_row(form.salaire) }}</div>
            <div class="col-6">{{ form_row(form.service) }}</div>
        </div>

         <div class="row">
            <div class="col">
                {{ form_row(form.date_naissance) }}
            </div>
        </div>
    <input type="submit" value="ajouter" class='btn btn-dark' >
    {{ form_end(form) }}
    </div>
</div>

{% endblock %}

templates/user/show_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!
{% endblock %}

{% block body %}

  {# {{ dump(user) }}  #}
 
 {# pour montrer tous les messages envoyer a un utilisateur, on fait une boucle#}
 
 <div class="container">
	{% for item in user.messages %}
		<p>{{ item.contenu }}</p>
	{% endfor %} 
  </div>



{% endblock %}

templates/user/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<div class="container d-flex justify-content-end mt-5">
<a  class="btn btn-primary d-inline-block float-right" href="{{path('app_add_user')}}"> Ajouter user</a>
</div>
<table class="table container">
			<thead>
				<tr>
					<th scope="col">Nom</th>
					<th scope="col">Prenom</th>
					<th scope="col">Ville</th>
					<th scope="col">email</th>
					<th scope="col">salaire</th>
					<th scope="col">Date de date naissance</th>
					<th>Action</th>
				</tr>
				</tr>
			</thead>
			<tbody>
				{% for user in liste_users %}
				 {# on utilise la  methode {{user.getNom}}ici mais twig la transformeen {{user.nom }} #}
					<tr>
						<td >{{ user.nom}}</td>
						<td>{{ user.Prenom }}</td>
						<td >{{ user.ville}}</td>
						<td >{{ user.email}}</td>
						<td>{{ user.salaire}}</td>
						<td>{{ user.dateNaissance |date('y-m-d')}}</td>

						<td>
						<a class="btn btn-primary" href="{{path('app_detail_user', {'id' : user.id}) }}">voir</a>
						<a   class="btn btn-danger" href="{{path('app_delete_user', {'id' : user.id}) }}">supprimer</a>
						<a  class="btn btn-warning" href="{{path('app_edit_user', {'id' : user.id}) }}">modiffier</a>
						<a  class="btn btn-info" href="{{path('app_message_new', {'id' : user.id}) }}">envoyer un message</a>
						
						
						
						
						
					</tr>
				{% endfor %}
			</tbody>
		</table>



{% endblock %}